#--------------------------------------------------------
# File: Makefile    Author(s): Simon Désaulniers
# 			       Frédéric Hamelin
# Date: 2013-12-19
#--------------------------------------------------------
# Makefile pour rapport en LaTeX
#--------------------------------------------------------

DOC=rapport

tex:
	pdflatex $(DOC).tex
clean:
	rm -f $(DOC).out $(DOC).toc $(DOC).aux $(DOC).log
